spring:
  application:
    name: CONFIG-SERVER-SERVICE


  cloud:
    config:
      server:
        git:
          uri: https://github.com/badsna/HotelReviewSystem-Config
          clone-on-start: true


server:
  port: 8085



