
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelReviewSystem_Rating_Service
    username: postgres
    password: By@$hna%
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
server:
  port: 8083


#okta configuration for  api gateway
#for authorization
okta:
  oauth2:
    issuer: https://dev-97346486.okta.com/oauth2/default
    audience: api://default


